### ISSUE TITLE
temporarily added cards shouldn't "change" a deck

### ISSUE THREAD

**Issue by pathmann** [supertriodo/Arena-Tracker#25] opened 2016-09-05 11:51 UTC
If you for example entomb a card, this card is added to your deck (awesome feature btw).

But this also sets the deck to a changed status (eg. Tracker asks to save changes made before quit), which imho should not happen, because after the game, the card will be removed from the deck in any cases.

At least here on linux amd 64 (gentoo).

**Comment by supertriodo** [comment] 2016-09-05 12:08
These temporary cards are removed from your deck when you end the game. If I understand correctly the problem is not that the deck list is incorrect, is just that the deck is marked as (has changes) so it ask you to save it when quitting.

Is this the problem?

**Comment by pathmann** [comment] 2016-09-05 12:10
Yes, that's right.

**Comment by supertriodo** [comment] 2016-09-05 12:16
Ok, I'll add it to my todo list, thx for the feedback!

**Comment by supertriodo** [comment] 2016-09-10 11:01
Fixed on [v4.11](https://github.com/supertriodo/Arena-Tracker/releases/tag/v4.11)

**Closed by supertriodo** 2016-09-10 11:01 UTC
