### ISSUE TITLE
No screen grab, and immediately crashes. 

### ISSUE THREAD

**Issue by zmccon** [supertriodo/Arena-Tracker#142] opened 2023-04-12 17:21 UTC
**got a new 4k monitor and now the whole app is broken. Screen not grabbing at all. Have reset everything, replaced the logs and added to the correct privacy settings.** 
 
**It will not read the heroes when I start the draft then after I manually select a new hero I get this:**

<img width="1397" alt="Screenshot 2023-04-12 at 1 09 34 PM" src="https://user-images.githubusercontent.com/43191688/231532891-4f849279-662a-4415-875b-6dd3e8604efd.png">

**discovered I have to increase the card in settings and then I get this:** 

<img width="1394" alt="Screenshot 2023-04-12 at 1 10 03 PM" src="https://user-images.githubusercontent.com/43191688/231533111-0f722207-4d14-4e88-899f-74a414f13183.png">

**No amount of refresh fixes it. So when I manually choose a card it freezes  like this for like 3 min of beach ball:** 

<img width="1373" alt="Screenshot 2023-04-12 at 1 10 46 PM" src="https://user-images.githubusercontent.com/43191688/231533680-8b9d0236-c125-490d-bdf9-fcb2120fd319.png">

**and then it finally just crashes with the usually "quit unexpectedly dialogue box:** 

<img width="1404" alt="Screenshot 2023-04-12 at 1 12 44 PM" src="https://user-images.githubusercontent.com/43191688/231533948-326c932a-f0dc-42ed-bf19-0aa3093e0e7c.png">

**This has been happening for the past couple days.** 

** What else do you need as far as logs or crash reports?**

**Comment by zmccon** [comment] 2023-04-12 17:27
**Here's the log from that instance.** 

13:09:29 - GameWatcher(53): LoadingScreen: GAME_MODE -> DRAFT
13:09:29 - GameWatcher(53): Entering ARENA (loadingScreenState = arena).
13:09:29 - DeckHandler: Enter arena
13:09:30 - DraftHandler: Hearthstone arena screen loaded from settings.
13:09:30 - DraftHandler: Create drafting windows.
13:09:30 - DraftScoreWindow: Scores - 1 row
13:09:30 - DraftHandler: Hearthstone arena screen loaded from settings.
13:09:30 - DraftHandler: Create drafting windows.
13:09:30 - DraftScoreWindow: Scores - 1 row
13:09:33 - DraftHandler: Hearthstone arena screen not found. Retrying...
13:09:36 - DraftHandler: Hearthstone arena screen not found. Retrying...
13:09:38 - DraftHandler: Hearthstone arena screen not found. Retrying...
13:09:42 - DraftHandler: Hearthstone arena screen not found. Retrying...
13:09:44 - DraftHandler: Choose: CORE_CS2_179_premium Sen'jin Shieldmasta 0.562
13:09:44 - DraftHandler: Choose: REV_841_premium Anonymous Informant 0.674
13:09:44 - DraftHandler: Choose: RLK_653_premium Infectious Ghoul 0.913
13:09:44 - DraftHandler: (1) CORE_CS2_179/REV_841/RLK_653 New codes.
13:09:44 - DraftHandler: reviewBestCards: manaRects/draftCards not ready.
13:09:45 - DraftHandler: Hearthstone arena screen not found. Retrying...
13:09:48 - DraftHandler: Hearthstone arena screen not found. Retrying...
13:09:51 - DraftHandler: Hearthstone arena screen not found. Retrying...
13:09:54 - DraftHandler: Hearthstone arena screen not found. Retrying...
13:09:57 - DraftHandler: Hearthstone arena screen not found. Retrying...
13:10:00 - DraftHandler: Hearthstone arena screen not found. Retrying...
13:10:03 - DraftHandler: Hearthstone arena screen not found. Retrying...
13:10:06 - DraftHandler: Hearthstone arena screen not found. Retrying...
13:10:10 - DraftHandler: Hearthstone arena screen not found. Retrying...
13:10:13 - DraftHandler: Hearthstone arena screen not found. Retrying...
13:10:17 - DraftHandler: Hearthstone arena screen not found. Retrying...
13:10:20 - DraftHandler: Hearthstone arena screen not found. Retrying...
13:10:23 - DraftHandler: Choose: CORE_CS2_179_premium Sen'jin Shieldmasta 0.562
13:10:23 - DraftHandler: Choose: REV_841_premium Anonymous Informant 0.674
13:10:23 - DraftHandler: Choose: RLK_653_premium Infectious Ghoul 0.913
13:10:23 - DraftHandler: (1) CORE_CS2_179/REV_841/RLK_653 New codes.
13:10:23 - DraftHandler: reviewBestCards: manaRects/draftCards not ready.
13:10:24 - DraftHandler: Hearthstone arena screen not found. Retrying...
13:10:27 - DraftHandler: Hearthstone arena screen not found. Retrying...
13:10:30 - DraftHandler: Hearthstone arena screen not found. Retrying...
13:10:33 - DraftHandler: Hearthstone arena screen not found. Retrying...
13:10:35 - DraftHandler: Hearthstone arena screen not found. Retrying...
13:10:38 - DraftHandler: Hearthstone arena screen not found. Retrying...

**Comment by zmccon** [comment] 2023-04-12 17:38
UPDATE: Doesn't work in either laptop display or external. But Fixed itself once I increased the card sized, quit the apps  disconnected the external and re ran everything without a secondary display. I know Ventura has had constant external display issues. Perhaps that has something to do with it. Is there something you think I could do to fix the problem myself? I would welcome the suggestions. Thank you!

**Comment by supertriodo** [comment] 2023-04-12 21:10
Hi there,

First, very well detailed and documented issue you wrote.

In the past people have had problems in Mac when having an external monitor connected. They often fix the problem by disconnecting it. 

Resetting AT could fix some settings stored so its a good idea to do if something crash. Changing the size of cards shouldn't have any effect on the draft overlay.

The latest log you posted seems all correct.

About the problem manually changing the card it's something is affecting more people as you saw on reddit. I'll see if I can reproduce the error on my end to fix it, the problem is I don't own a mac and compile AT on a virtual machine that's why my testing capabilities are very limited.

Thanks for reaching out, for the feedback and your patreon support!
Triodo

**Comment by zmccon** [comment] 2023-04-14 07:05
Thank you! Disconnecting the monitor worked for me. Let me know if if there's anything I can do/provide to assist in addressing the other issue. Cheers!

**Comment by supertriodo** [comment] 2023-04-14 09:49
I've been able to reproduce the crash on my VM, It seems it only occurs when pressing enter after manually typing the card. If you press tab key it goes well. That could mean there is some bug in qt mac related to losing focus on elements.

**Comment by supertriodo** [comment] 2023-04-16 08:49
Ok, a fix is in the oven, if you could try it out, it works well in my VM.

https://www.patreon.com/posts/manually-card-by-81585446?utm_medium=clipboard_copy&utm_source=copyLink&utm_campaign=postshare_creator&utm_content=join_link

**Comment by supertriodo** [comment] 2023-04-25 08:37
Version 23.04.01 should fix the problem 
https://github.com/supertriodo/Arena-Tracker/releases/tag/v23.04.01

**Closed by supertriodo** 2023-04-25 08:37 UTC
